/**
 * Enumerating the possible states a game can be in.
 */
export const GAME_STATUS_WAITING_FOR_FIRST_FLIP = "GAME_STATUS_WAITING_FOR_FIRST_FLIP";
export const GAME_STATUS_WAITING_FOR_SECOND_FLIP = "GAME_STATUS_WAITING_FOR_SECOND_FLIP";
export const GAME_STATUS_FINISHED = "GAME_STATUS_FINISHED";
export const GAME_STATUS_TURN_ENDED = "GAME_STATUS_TURN_ENDED";
